#!/usr/bin/env python3
# Author: Pekka Marjamäki - Suolenkainen
# https://github.com/suolenkainen/market

from data import PRODUCT, PEOPLE, PEOPLE_PRODUCT, PRODUCERS, STORAGE, PURCHASE_ORDERS, SALES_ORDERS
from data import PRODUCT_ID, PEOPLE_ID, PRODUCERS_ID, PURCHASE_ORDERS_ID, SALES_ORDERS_ID

print(PRODUCT, PRODUCERS, PEOPLE, PEOPLE_PRODUCT,STORAGE, PURCHASE_ORDERS, SALES_ORDERS)
print(PRODUCT_ID, PEOPLE_ID, PRODUCERS_ID, PURCHASE_ORDERS_ID, SALES_ORDERS_ID)

# Create a purchase

# 
